// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcIHAkyGoJcDf1KVW9RX9DpRI3WHXymfI',
    appId: '1:791215781657:web:ca5234c50deafd3cb9f788',
    messagingSenderId: '791215781657',
    projectId: 'breakout-room5',
    authDomain: 'breakout-room5.firebaseapp.com',
    storageBucket: 'breakout-room5.firebasestorage.app',
    measurementId: 'G-5FSGRTQFF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkPUi0wdM13FNOZjQCojJl3WKhi_jzMdM',
    appId: '1:791215781657:android:5b8bfd1a6a990399b9f788',
    messagingSenderId: '791215781657',
    projectId: 'breakout-room5',
    storageBucket: 'breakout-room5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkjK-r3dqtkdidRDRCFqBfFC6wYunbavI',
    appId: '1:791215781657:ios:a0b9c56065ac344bb9f788',
    messagingSenderId: '791215781657',
    projectId: 'breakout-room5',
    storageBucket: 'breakout-room5.firebasestorage.app',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkjK-r3dqtkdidRDRCFqBfFC6wYunbavI',
    appId: '1:791215781657:ios:a0b9c56065ac344bb9f788',
    messagingSenderId: '791215781657',
    projectId: 'breakout-room5',
    storageBucket: 'breakout-room5.firebasestorage.app',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcIHAkyGoJcDf1KVW9RX9DpRI3WHXymfI',
    appId: '1:791215781657:web:1b966d64caab92e6b9f788',
    messagingSenderId: '791215781657',
    projectId: 'breakout-room5',
    authDomain: 'breakout-room5.firebaseapp.com',
    storageBucket: 'breakout-room5.firebasestorage.app',
    measurementId: 'G-K1VQ0BZ3Q9',
  );
}
